[project]
name = "serrf-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "rpy2>=3.6.4",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.1",
]

[project.scripts]
serrf-py = "serrf_py:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
